### ISSUE TITLE
removing --symlink-install on windows not working as expected

### ISSUE THREAD

**Issue by flynneva** [deitry/vscode-colcon-helper#30]
I am getting this error from vs code tasks after trying to edit the `tasks.json` file like in the README on windows:

```
Error: The colcon task detection didn't contribute a task for the following configuration:
{
    "type": "colcon",
    "args": [
        "build"
    ],
    "group": "build",
    "problemMatcher": [],
    "label": "colcon: build"
}
The task will be ignored.
```

any tips on how to edit the `tasks.json` file correctly?

**Comment by deitry** [comment]
You didn't provide `task` parameter. Here's my configuration:

```jsonc
{
	"type": "colcon",
	"task": "build",
	"args": [
		"build",
		"--event-handlers",
		"console_direct+",
		// "--symlink-install",
	],
	"group": "build",
	"problemMatcher": [],
	"label": "colcon: build with log",
	"presentation": {
		"echo": true,
		"reveal": "always",
		"focus": false,
		"panel": "dedicated",
		"showReuseMessage": true,
		"clear": true,
	}
}
```

Though I can't remember why it have to be specified; it seems a bit duplicating.

**Comment by deitry** [comment]
Ah, it's from that time when arguments were passed through workspace configuration settings. I will try to remove `task` parameter requirement in the future releases.

**Comment by deitry** [comment]
Just pushed 1.2.0 with dropped support of `colcon.*Args` configuration options. Also removed `task` property of task definition since it's not used anymore.

https://github.com/deitry/vscode-colcon-helper/commit/19685500d3367b40cbd5f3d2b14aed8651d17cd0

**Comment by flynneva** [comment]
so after updating the extension  on windows and trying to edit the task to remove `--symlink-install`, i'm getting this output into the `task.json`:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "colcon",
			"command": "colcon",
			"args": [
				"--workspace",
				"d:\\code\\projects\\ros",
				"build"
			],
			"group": "build",
			"problemMatcher": [],
			"label": "colcon: build"
		}
	]
}
```

and an error that says:

```
Error: The colcon task detection didn't contribute a task for the following configuration:
{
    "type": "colcon",
    "command": "colcon",
    "args": [
        "build"
    ],
    "group": "build",
    "problemMatcher": [],
    "label": "colcon: build"
}
The task will be ignored.
```

**Comment by flynneva** [comment]
im going to try to copy & paste your `task.json` config into mine and see if that fixes it. 

UPDATE: didn't work...same error.

**Comment by deitry** [comment]
Does your `tasks.json` contains other tasks? 

---

I was able to run your task, but get errors with `colcon` arguments:
```
> Executing task: C:\Python38\Scripts\colcon.exe --workspace d:\prog\ros2test build <

usage: C:\Python38\Scripts\colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
                                  {build,extension-points,extensions,graph,info,list,metadata,test,test-result,version-check}
                                  ...
C:\Python38\Scripts\colcon: error: argument verb_name: invalid choice: '--workspace' (choose from 'build', 'extension-points', 'extensions', 'graph', 'info', 'list', 'metadata', 'test', 'test-result', 'version-check')       
The terminal process "C:\Python38\Scripts\colcon.exe '--workspace', 'd:\prog\ros2test', 'build'" terminated with exit code: 2.
```

or with switched arguments order:
```
> Executing task: C:\Python38\Scripts\colcon.exe build --workspace d:\prog\ros2test <

usage: C:\Python38\Scripts\colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
                                  {build,extension-points,extensions,graph,info,list,metadata,test,test-result,version-check}
                                  ...
C:\Python38\Scripts\colcon: error: unrecognized arguments: --workspace d:\prog\ros2test
The terminal process "C:\Python38\Scripts\colcon.exe 'build', '--workspace', 'd:\prog\ros2test'" terminated with exit code: 2.
```

**Comment by flynneva** [comment]
@deitry it does not contain other tasks...just the one i copied above. do you have to restart vs code or something to have it take affect?

**Comment by deitry** [comment]
Yes, you can try to restart VS Code. Good old advice for any kind of IT thing :D

And just to be sure. You spelled file name as `task.json`, without `s`. Actual file name for tasks is spelled as `taskS.json`. Could it be that you have both in your workspace?

**Comment by deitry** [comment]
If restart does not help, could you please look into Output pane? There is a picker where you can select Colcon Tasks extension log and also VS Code Extension Host log. If extension cannot be properly initialized, there may be some errors

**Comment by flynneva** [comment]
looking at the VS Code Extensions log in the output:

```
[2021-04-20 08:13:15.025] [exthost] [error] Activating extension deitry.colcon-helper failed due to an error:
[2021-04-20 08:13:15.025] [exthost] [error] TypeError: Cannot read property 'endsWith' of null
	at Config.getCurrentShellType (c:\Users\uidp8702\.vscode\extensions\deitry.colcon-helper-1.2.0\out\colcon_config.js:281:24)
	at Config.getSourceCmd (c:\Users\uidp8702\.vscode\extensions\deitry.colcon-helper-1.2.0\out\colcon_config.js:345:22)
	at sourceIfExists (c:\Users\uidp8702\.vscode\extensions\deitry.colcon-helper-1.2.0\out\environment.js:21:41)
	at c:\Users\uidp8702\.vscode\extensions\deitry.colcon-helper-1.2.0\out\environment.js:33:16
	at Array.forEach (<anonymous>)
	at Object.refreshEnvironment (c:\Users\uidp8702\.vscode\extensions\deitry.colcon-helper-1.2.0\out\environment.js:32:39)
	at activate (c:\Users\uidp8702\.vscode\extensions\deitry.colcon-helper-1.2.0\out\extension.js:250:23)
	at Function._callActivateOptional (c:\Users\uidp8702\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:14382)
	at Function._callActivate (c:\Users\uidp8702\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:14051)
	at c:\Users\uidp8702\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12203
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 2)
	at async Promise.all (index 0)
```

**Comment by flynneva** [comment]
Looking at the VS Code Extensions log...there is this error that seems probably like the problem:

```
[2021-04-20 08:13:15.025] [exthost] [error] Activating extension deitry.colcon-helper failed due to an error:
[2021-04-20 08:13:15.025] [exthost] [error] TypeError: Cannot read property 'endsWith' of null
	at Config.getCurrentShellType (c:\Users\UID\.vscode\extensions\deitry.colcon-helper-1.2.0\out\colcon_config.js:281:24)
	at Config.getSourceCmd (c:\Users\UID\.vscode\extensions\deitry.colcon-helper-1.2.0\out\colcon_config.js:345:22)
	at sourceIfExists (c:\Users\UID\.vscode\extensions\deitry.colcon-helper-1.2.0\out\environment.js:21:41)
	at c:\Users\UID\.vscode\extensions\deitry.colcon-helper-1.2.0\out\environment.js:33:16
	at Array.forEach (<anonymous>)
	at Object.refreshEnvironment (c:\Users\UID\.vscode\extensions\deitry.colcon-helper-1.2.0\out\environment.js:32:39)
	at activate (c:\Users\UID\.vscode\extensions\deitry.colcon-helper-1.2.0\out\extension.js:250:23)
	at Function._callActivateOptional (c:\Users\UID\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:14382)
	at Function._callActivate (c:\Users\UID\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:14051)
	at c:\Users\UID\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12203
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 2)
	at async Promise.all (index 0)
```

**Comment by deitry** [comment]
Thank you

Will fix it soon.

Right now you may try to set `terminal.integrated.shell.windows` or `colcon.shell.windows`

**Comment by flynneva** [comment]
no problem, thank you for such an awesome extension!!! im excited for what we can do with it going forward

**Comment by flynneva** [comment]
@deitry setting `colcon.shell.windows` to the path to my VS 2019 developer terminal worked! now the task is changing when I change the `task.json` file. awesome, thank you so much.

**Comment by deitry** [comment]
Just added a better handling if there is no shell config at all, but yeah, it's better to provide it explicitly.

https://github.com/deitry/vscode-colcon-helper/commit/cba7377b95b19922d93a6e09278f08a5af353599

I think I can close it safely now
